# Generated by Django 5.0.6 on 2024-07-27 23:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('idEquipment', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('level', models.IntegerField(choices=[(-1, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=-1, verbose_name='Nivel')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('guideNumber', models.IntegerField(default=0, verbose_name='Número de Guía')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('creationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('stock', models.IntegerField(default=0)),
                ('guideNumber', models.IntegerField(default=0, verbose_name='Número de Guía')),
                ('unit', models.CharField(default='', max_length=20, verbose_name='Unidad')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('creationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PpeLoan',
            fields=[
                ('idPpeLoan', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('loanDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega')),
                ('newLoanDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nueva Entrega')),
                ('manager', models.CharField(default='', max_length=20, verbose_name='Nombre del Responsable')),
                ('description', models.TextField(default='Es su primera entrega.', verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('idTool', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('level', models.IntegerField(choices=[(-1, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=-1, verbose_name='Nivel')),
                ('stock', models.IntegerField(default=0)),
                ('guideNumber', models.IntegerField(default=0, verbose_name='Número de Guía')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('creationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('dni', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('position', models.CharField(default=None, max_length=20)),
                ('contractDate', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('workerStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ppe',
            fields=[
                ('idPpe', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('unitCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('guideNumber', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('creationDate', models.DateField(null=True)),
                ('duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.duration')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PpeLoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('ppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.ppe')),
                ('ppeLoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='almacen.ppeloan')),
            ],
        ),
        migrations.AddField(
            model_name='ppeloan',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.worker'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('idLoan', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('workOrderCode', models.IntegerField(default=0, verbose_name='Código de Órden de Trabajo')),
                ('loanDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega')),
                ('returnLoanDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución')),
                ('loanStatus', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.equipment')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.material')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.tool')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.worker')),
            ],
        ),
    ]
