<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-08-01 03:28
=======
# Generated by Django 5.0.6 on 2024-07-31 20:58
>>>>>>> 81d01ba93351f5fccfc1ef7b8bb5dce3f33b2234

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('idEquipment', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('loanAmount', models.IntegerField(default=0)),
                ('level', models.IntegerField(choices=[(-1, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=-1, verbose_name='Nivel')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('guideNumber', models.IntegerField(default=0, verbose_name='Número de Guía')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('serialNumber', models.IntegerField(default=0, verbose_name='Stock')),
                ('creationDate', models.DateField()),
                ('unitCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('idTool', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('loanAmount', models.IntegerField(default=0)),
                ('level', models.IntegerField(choices=[(-1, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=1, verbose_name='Nivel')),
                ('stock', models.IntegerField(default=0)),
                ('guideNumber', models.IntegerField(default=0, verbose_name='Número de Guía')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('unitCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('dni', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('position', models.CharField(default=None, max_length=20)),
                ('contractDate', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('workerStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ppe',
            fields=[
                ('idPpe', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unitCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('guideNumber', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('serialNumber', models.IntegerField(default=0, verbose_name='Stock')),
                ('creationDate', models.DateField(null=True)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('loanAmount', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('guideNumber', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('creationDate', models.DateField(auto_now_add=True, null=True)),
                ('unitCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PpeLoan',
            fields=[
                ('idPpeLoan', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('workerPosition', models.CharField(max_length=100, null=True)),
                ('workerDni', models.CharField(max_length=20, null=True)),
                ('loanDate', models.DateField(default=django.utils.timezone.now)),
                ('newLoanDate', models.DateField(default=django.utils.timezone.now)),
                ('manager', models.CharField(default='', max_length=20)),
                ('loanAmount', models.IntegerField(default=0)),
                ('confirmed', models.BooleanField(default=False)),
                ('ppe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.ppe')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='almacen.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('idLoan', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('workOrderCode', models.IntegerField(default=0, verbose_name='Código de Órden de Trabajo')),
                ('loanDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega')),
                ('returnLoanDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución')),
                ('loanStatus', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.equipment')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.material')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.tool')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.worker')),
            ],
        ),
    ]
