# Generated by Django 5.0.6 on 2024-07-29 03:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('idEquipment', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('level', models.IntegerField(choices=[(-1, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=-1, verbose_name='Nivel')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('guideNumber', models.IntegerField(default=0, verbose_name='Número de Guía')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('creationDate', models.DateField()),
                ('unitCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0)),
                ('guideNumber', models.IntegerField(default=0)),
                ('unit', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('creationDate', models.DateField()),
                ('unitCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ppe',
            fields=[
                ('idPpe', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('unitCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('guideNumber', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('creationDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PpeLoan',
            fields=[
                ('idPpeLoan', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('loanDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega')),
                ('newLoanDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nueva Entrega')),
                ('manager', models.CharField(default='', max_length=20, verbose_name='Nombre del Responsable')),
                ('description', models.TextField(default='Es su primera entrega.', verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('idTool', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('level', models.IntegerField(choices=[(-1, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=-1, verbose_name='Nivel')),
                ('stock', models.IntegerField(default=0)),
                ('guideNumber', models.IntegerField(default=0, verbose_name='Número de Guía')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('creationDate', models.DateField()),
                ('unitCost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('dni', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('position', models.CharField(default=None, max_length=20)),
                ('contractDate', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('workerStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=9)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PpeLoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('ppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.ppe')),
                ('ppeLoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='almacen.ppeloan')),
            ],
        ),
        migrations.AddField(
            model_name='ppe',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.unit'),
        ),
        migrations.AddField(
            model_name='ppeloan',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.worker'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('idLoan', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('workOrderCode', models.IntegerField(default=0, verbose_name='Código de Órden de Trabajo')),
                ('loanDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega')),
                ('returnLoanDate', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución')),
                ('loanStatus', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.equipment')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.material')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.tool')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.worker')),
            ],
        ),
    ]
