# Generated by Django 5.0.6 on 2024-07-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='creationDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
