# Generated by Django 5.0.6 on 2024-08-01 04:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serialNumber',
            field=models.IntegerField(default=0, verbose_name='Número de Serie'),
        ),
    ]
