# Generated by Django 5.0.6 on 2024-07-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_duration_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppe',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
