# Generated by Django 5.0.6 on 2024-07-30 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.unit'),
        ),
    ]
