# Generated by Django 5.0.6 on 2024-07-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='model_name',
            new_name='content_type',
        ),
        migrations.RemoveField(
            model_name='history',
            name='additional_info',
        ),
    ]
