# Generated by Django 5.0.6 on 2024-07-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_alter_history_action_alter_history_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='object_id',
            field=models.CharField(max_length=255),
        ),
    ]
