# Generated by Django 5.0.6 on 2024-08-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_alter_history_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='creationDate',
        ),
        migrations.AlterField(
            model_name='tool',
            name='level',
            field=models.IntegerField(choices=[(-1, 'Elija un nivel'), (1, 'Bajo'), (2, 'Medio'), (3, 'Mayor')], default=1, verbose_name='Nivel'),
        ),
    ]
